//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtoProstoZhest
{
    using shabl;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Contexts;

    public partial class champ_user_04Entities : DbContext
    {
        public static champ_user_04Entities _context;
        public champ_user_04Entities()
            : base("name=champ_user_04Entities")
        {
        }
        public static champ_user_04Entities GetContext()
        {
            if (_context == null)
                _context = new champ_user_04Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Jury_Activity> Jury_Activity { get; set; }
        public virtual DbSet<Participants_Activity> Participants_Activity { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
